FROM public.ecr.aws/docker/library/node:16 AS lib-builder
# FROM node:16-alpine AS lib-builder
WORKDIR /app
COPY ./bo-bsff-frontend-common/package*.json ./
COPY ./bo-bsff-frontend-common/yarn.lock ./
RUN yarn
COPY ./bo-bsff-frontend-common .
RUN yarn build-plugin

FROM public.ecr.aws/docker/library/node:16 AS builder
# FROM node:16-alpine AS builder
WORKDIR /app
COPY ./package*.json ./
COPY ./yarn.lock ./
RUN yarn
COPY . .
COPY --from=lib-builder /app/dist /app/bo-bsff-frontend-common/dist
RUN yarn build

FROM public.ecr.aws/nginx/nginx:alpine
# FROM nginx:alpine
RUN mkdir /app
COPY --from=builder /app/dist /app
COPY nginx.conf /etc/nginx/conf.d/default.conf


FROM public.ecr.aws/docker/library/node:16 AS lib-builder
FROM node:16-alpine AS lib-builder
WORKDIR /app
COPY ./bo-bsff-frontend-common/package*.json ./
COPY ./bo-bsff-frontend-common/yarn.lock ./
RUN yarn
COPY ./bo-bsff-frontend-common .
RUN yarn build-plugin