FROM public.ecr.aws/docker/library/node:16 AS builder
# FROM node:16-alpine AS builder
WORKDIR /app
COPY ./package*.json ./
COPY ./yarn.lock ./
RUN yarn
COPY . .
WORKDIR /app/bo-bsff-frontend-common
RUN yarn
RUN yarn build-plugin
WORKDIR /app
RUN yarn build

FROM public.ecr.aws/nginx/nginx:alpine
# FROM nginx:alpine
RUN mkdir /app
COPY --from=builder /app/dist /app
COPY nginx.conf /etc/nginx/conf.d/default.conf

