FROM public.ecr.aws/docker/library/node:16 AS builder
WORKDIR /app
COPY ./package*.json ./
COPY ./yarn.lock ./
RUN yarn
COPY . .
RUN yarn build:cc-st

FROM public.ecr.aws/nginx/nginx:alpine
RUN mkdir /app
COPY --from=builder /app/dist /app
COPY nginx.conf /etc/nginx/conf.d/default.conf
