/**
 * カテゴリコード
 */
export default async (context, inject) => {
  inject("categories", {
    // 大カテゴリより地図基盤のアイコン定義書にあるiconNoを取得する
    getCatExlCd(catLrg, catMid, catSml) {
      const target = categoriesMap.filter(x => {
        return x.catLrgCd == catLrg
            && x.catMidCd == catMid
            && x.catSmlCd == catSml
      });
      return target.length == 0 ? null : target[0];
    }
  });
};

// カテゴリ定義（新BSURL構成について.xlsxより）
const categoriesMap = [
  {catExlCd: 'skillup', catExlNm: 'スキルアップ', catLrgCd: '004', catLrgNm: '学ぶ', catMidCd: '007', catMidNm: '外国語・留学', catSmlCd: '003', catSmlNm: '語学スクール'},
  {catExlCd: 'skillup', catExlNm: 'スキルアップ', catLrgCd: '004', catLrgNm: '学ぶ', catMidCd: '007', catMidNm: '外国語・留学', catSmlCd: '004', catSmlNm: 'オンライン英会話'},
  {catExlCd: 'skillup', catExlNm: 'スキルアップ', catLrgCd: '004', catLrgNm: '学ぶ', catMidCd: '007', catMidNm: '外国語・留学', catSmlCd: '005', catSmlNm: '教材・通信講座'},
  {catExlCd: 'skillup', catExlNm: 'スキルアップ', catLrgCd: '004', catLrgNm: '学ぶ', catMidCd: '007', catMidNm: '外国語・留学', catSmlCd: '006', catSmlNm: '留学・その他'},
  {catExlCd: 'skillup', catExlNm: 'スキルアップ', catLrgCd: '004', catLrgNm: '学ぶ', catMidCd: '008', catMidNm: 'オリジナル企画', catSmlCd: '003', catSmlNm: 'その他学ぶ企画'},
  {catExlCd: 'skillup', catExlNm: 'スキルアップ', catLrgCd: '004', catLrgNm: '学ぶ', catMidCd: '009', catMidNm: '趣味・カルチャースクール', catSmlCd: '001', catSmlNm: '趣味・カルチャースクール'},
  {catExlCd: 'skillup', catExlNm: 'スキルアップ', catLrgCd: '004', catLrgNm: '学ぶ', catMidCd: '010', catMidNm: '資格取得', catSmlCd: '001', catSmlNm: '資格取得'},
  {catExlCd: 'skillup', catExlNm: 'スキルアップ', catLrgCd: '004', catLrgNm: '学ぶ', catMidCd: '011', catMidNm: 'ビジネススキル', catSmlCd: '001', catSmlNm: 'ビジネススキル'},
  {catExlCd: 'skillup', catExlNm: 'スキルアップ', catLrgCd: '004', catLrgNm: '学ぶ', catMidCd: '012', catMidNm: 'IT・パソコン', catSmlCd: '001', catSmlNm: 'IT・パソコン'},
  {catExlCd: 'shopping', catExlNm: '買い物', catLrgCd: '029', catLrgNm: 'ショッピング', catMidCd: '003', catMidNm: 'ネットショップ', catSmlCd: '001', catSmlNm: 'スポーツ用品'},
  {catExlCd: 'shopping', catExlNm: '買い物', catLrgCd: '029', catLrgNm: 'ショッピング', catMidCd: '003', catMidNm: 'ネットショップ', catSmlCd: '002', catSmlNm: '家具'},
  {catExlCd: 'shopping', catExlNm: '買い物', catLrgCd: '029', catLrgNm: 'ショッピング', catMidCd: '003', catMidNm: 'ネットショップ', catSmlCd: '003', catSmlNm: '家電'},
  {catExlCd: 'shopping', catExlNm: '買い物', catLrgCd: '029', catLrgNm: 'ショッピング', catMidCd: '003', catMidNm: 'ネットショップ', catSmlCd: '004', catSmlNm: 'ビジネススーツ'},
  {catExlCd: 'shopping', catExlNm: '買い物', catLrgCd: '029', catLrgNm: 'ショッピング', catMidCd: '003', catMidNm: 'ネットショップ', catSmlCd: '005', catSmlNm: 'ファッション'},
  {catExlCd: 'shopping', catExlNm: '買い物', catLrgCd: '029', catLrgNm: 'ショッピング', catMidCd: '003', catMidNm: 'ネットショップ', catSmlCd: '006', catSmlNm: 'メガネ・コンタクト'},
  {catExlCd: 'shopping', catExlNm: '買い物', catLrgCd: '029', catLrgNm: 'ショッピング', catMidCd: '003', catMidNm: 'ネットショップ', catSmlCd: '007', catSmlNm: '美容・コスメ'},
  {catExlCd: 'shopping', catExlNm: '買い物', catLrgCd: '029', catLrgNm: 'ショッピング', catMidCd: '003', catMidNm: 'ネットショップ', catSmlCd: '008', catSmlNm: '百貨店'},
  {catExlCd: 'shopping', catExlNm: '買い物', catLrgCd: '029', catLrgNm: 'ショッピング', catMidCd: '003', catMidNm: 'ネットショップ', catSmlCd: '009', catSmlNm: '雑貨'},
  {catExlCd: 'shopping', catExlNm: '買い物', catLrgCd: '029', catLrgNm: 'ショッピング', catMidCd: '003', catMidNm: 'ネットショップ', catSmlCd: '010', catSmlNm: '食料・飲料'},
  {catExlCd: 'shopping', catExlNm: '買い物', catLrgCd: '029', catLrgNm: 'ショッピング', catMidCd: '003', catMidNm: 'ネットショップ', catSmlCd: '011', catSmlNm: 'ブランド品'},
  {catExlCd: 'shopping', catExlNm: '買い物', catLrgCd: '029', catLrgNm: 'ショッピング', catMidCd: '003', catMidNm: 'ネットショップ', catSmlCd: '013', catSmlNm: 'その他ネットショップ'},
  {catExlCd: 'shopping', catExlNm: '買い物', catLrgCd: '029', catLrgNm: 'ショッピング', catMidCd: '003', catMidNm: 'ネットショップ', catSmlCd: '014', catSmlNm: '新聞・書籍・雑誌'},
  {catExlCd: 'shopping', catExlNm: '買い物', catLrgCd: '029', catLrgNm: 'ショッピング', catMidCd: '003', catMidNm: 'ネットショップ', catSmlCd: '016', catSmlNm: 'ベネポ交換'},
  {catExlCd: 'shopping', catExlNm: '買い物', catLrgCd: '029', catLrgNm: 'ショッピング', catMidCd: '003', catMidNm: 'ネットショップ', catSmlCd: '017', catSmlNm: 'Webサービス'},
  {catExlCd: 'shopping', catExlNm: '買い物', catLrgCd: '029', catLrgNm: 'ショッピング', catMidCd: '003', catMidNm: 'ネットショップ', catSmlCd: '018', catSmlNm: '総合ECサイト'},
  {catExlCd: 'shopping', catExlNm: '買い物', catLrgCd: '029', catLrgNm: 'ショッピング', catMidCd: '004', catMidNm: '店舗', catSmlCd: '001', catSmlNm: 'スポーツ用品'},
  {catExlCd: 'shopping', catExlNm: '買い物', catLrgCd: '029', catLrgNm: 'ショッピング', catMidCd: '004', catMidNm: '店舗', catSmlCd: '002', catSmlNm: '百貨店'},
  {catExlCd: 'shopping', catExlNm: '買い物', catLrgCd: '029', catLrgNm: 'ショッピング', catMidCd: '004', catMidNm: '店舗', catSmlCd: '003', catSmlNm: '家具'},
  {catExlCd: 'shopping', catExlNm: '買い物', catLrgCd: '029', catLrgNm: 'ショッピング', catMidCd: '004', catMidNm: '店舗', catSmlCd: '004', catSmlNm: '家電'},
  {catExlCd: 'shopping', catExlNm: '買い物', catLrgCd: '029', catLrgNm: 'ショッピング', catMidCd: '004', catMidNm: '店舗', catSmlCd: '005', catSmlNm: 'ビジネススーツ'},
  {catExlCd: 'shopping', catExlNm: '買い物', catLrgCd: '029', catLrgNm: 'ショッピング', catMidCd: '004', catMidNm: '店舗', catSmlCd: '007', catSmlNm: 'ファッション'},
  {catExlCd: 'shopping', catExlNm: '買い物', catLrgCd: '029', catLrgNm: 'ショッピング', catMidCd: '004', catMidNm: '店舗', catSmlCd: '008', catSmlNm: 'メガネ・コンタクト'},
  {catExlCd: 'shopping', catExlNm: '買い物', catLrgCd: '029', catLrgNm: 'ショッピング', catMidCd: '004', catMidNm: '店舗', catSmlCd: '009', catSmlNm: '雑貨'},
  {catExlCd: 'shopping', catExlNm: '買い物', catLrgCd: '029', catLrgNm: 'ショッピング', catMidCd: '004', catMidNm: '店舗', catSmlCd: '010', catSmlNm: '美容・コスメ'},
  {catExlCd: 'shopping', catExlNm: '買い物', catLrgCd: '029', catLrgNm: 'ショッピング', catMidCd: '004', catMidNm: '店舗', catSmlCd: '011', catSmlNm: 'ブランド品'},
  {catExlCd: 'shopping', catExlNm: '買い物', catLrgCd: '029', catLrgNm: 'ショッピング', catMidCd: '004', catMidNm: '店舗', catSmlCd: '013', catSmlNm: 'その他販売'},
  {catExlCd: 'shopping', catExlNm: '買い物', catLrgCd: '029', catLrgNm: 'ショッピング', catMidCd: '004', catMidNm: '店舗', catSmlCd: '013', catSmlNm: 'その他販売'},
  {catExlCd: 'shopping', catExlNm: '買い物', catLrgCd: '029', catLrgNm: 'ショッピング', catMidCd: '004', catMidNm: '店舗', catSmlCd: '013', catSmlNm: 'その他販売'},
  {catExlCd: 'shopping', catExlNm: '買い物', catLrgCd: '029', catLrgNm: 'ショッピング', catMidCd: '004', catMidNm: '店舗', catSmlCd: '013', catSmlNm: 'その他販売'},
  {catExlCd: 'shopping', catExlNm: '買い物', catLrgCd: '029', catLrgNm: 'ショッピング', catMidCd: '004', catMidNm: '店舗', catSmlCd: '014', catSmlNm: 'その他'},
  {catExlCd: 'shopping', catExlNm: '買い物', catLrgCd: '029', catLrgNm: 'ショッピング', catMidCd: '005', catMidNm: '定期購読', catSmlCd: '001', catSmlNm: 'ビジネス誌'},
  {catExlCd: 'shopping', catExlNm: '買い物', catLrgCd: '029', catLrgNm: 'ショッピング', catMidCd: '005', catMidNm: '定期購読', catSmlCd: '002', catSmlNm: '一般誌'},
  {catExlCd: 'shopping', catExlNm: '買い物', catLrgCd: '029', catLrgNm: 'ショッピング', catMidCd: '005', catMidNm: '定期購読', catSmlCd: '003', catSmlNm: 'スポーツ誌'},
  {catExlCd: 'shopping', catExlNm: '買い物', catLrgCd: '029', catLrgNm: 'ショッピング', catMidCd: '006', catMidNm: '書籍･新聞', catSmlCd: '001', catSmlNm: '新聞'},
  {catExlCd: 'shopping', catExlNm: '買い物', catLrgCd: '029', catLrgNm: 'ショッピング', catMidCd: '006', catMidNm: '書籍･新聞', catSmlCd: '002', catSmlNm: '書籍・雑誌'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '002', catLrgNm: 'スポーツ', catMidCd: '007', catMidNm: 'フィットネス', catSmlCd: '001', catSmlNm: 'フィットネス'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '002', catLrgNm: 'スポーツ', catMidCd: '007', catMidNm: 'フィットネス', catSmlCd: '004', catSmlNm: 'ヨガ・ピラティス・加圧トレーニング'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '002', catLrgNm: 'スポーツ', catMidCd: '008', catMidNm: 'ゴルフ', catSmlCd: '001', catSmlNm: 'ゴルフ場'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '002', catLrgNm: 'スポーツ', catMidCd: '008', catMidNm: 'ゴルフ', catSmlCd: '002', catSmlNm: 'ゴルフスクール'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '002', catLrgNm: 'スポーツ', catMidCd: '009', catMidNm: 'テニス', catSmlCd: '001', catSmlNm: 'テニス場'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '002', catLrgNm: 'スポーツ', catMidCd: '009', catMidNm: 'テニス', catSmlCd: '002', catSmlNm: 'テニススクール'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '002', catLrgNm: 'スポーツ', catMidCd: '012', catMidNm: 'アウトドア', catSmlCd: '001', catSmlNm: 'スキー･スノーボード'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '002', catLrgNm: 'スポーツ', catMidCd: '012', catMidNm: 'アウトドア', catSmlCd: '002', catSmlNm: 'マリンスポーツ'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '002', catLrgNm: 'スポーツ', catMidCd: '012', catMidNm: 'アウトドア', catSmlCd: '003', catSmlNm: '乗馬'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '002', catLrgNm: 'スポーツ', catMidCd: '013', catMidNm: 'その他スポーツ', catSmlCd: '001', catSmlNm: 'その他スポーツ・スポーツ施設'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '002', catLrgNm: 'スポーツ', catMidCd: '013', catMidNm: 'その他スポーツ', catSmlCd: '002', catSmlNm: 'マラソン'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '002', catLrgNm: 'スポーツ', catMidCd: '015', catMidNm: 'サッカー・フットサル', catSmlCd: '001', catSmlNm: 'サッカー・フットサル'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '005', catLrgNm: 'リラク・ビューティー', catMidCd: '001', catMidNm: 'エステ', catSmlCd: '001', catSmlNm: 'エステ'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '005', catLrgNm: 'リラク・ビューティー', catMidCd: '001', catMidNm: 'エステ', catSmlCd: '002', catSmlNm: 'スパ・ホテルエステ'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '005', catLrgNm: 'リラク・ビューティー', catMidCd: '005', catMidNm: 'リラクサロン', catSmlCd: '001', catSmlNm: 'リラクサロン'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '005', catLrgNm: 'リラク・ビューティー', catMidCd: '006', catMidNm: 'ヘアケア', catSmlCd: '001', catSmlNm: 'ヘアケア'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '005', catLrgNm: 'リラク・ビューティー', catMidCd: '007', catMidNm: '情報予約サイト', catSmlCd: '001', catSmlNm: '情報予約サイト'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '005', catLrgNm: 'リラク・ビューティー', catMidCd: '009', catMidNm: 'ヘアサロン', catSmlCd: '001', catSmlNm: 'ヘアサロン'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '005', catLrgNm: 'リラク・ビューティー', catMidCd: '010', catMidNm: 'ネイルサロン・アイビューティ', catSmlCd: '001', catSmlNm: 'ネイルサロン'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '005', catLrgNm: 'リラク・ビューティー', catMidCd: '010', catMidNm: 'ネイルサロン・アイビューティ', catSmlCd: '002', catSmlNm: 'アイビューティー'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '005', catLrgNm: 'リラク・ビューティー', catMidCd: '011', catMidNm: 'その他リラク・ビューティー', catSmlCd: '001', catSmlNm: 'その他リラク・ビューティー'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '005', catLrgNm: 'リラク・ビューティー', catMidCd: '012', catMidNm: '日帰り温泉・スパ', catSmlCd: '001', catSmlNm: '日帰り温泉・スパ'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '006', catLrgNm: '法人向けサービス', catMidCd: '004', catMidNm: 'その他', catSmlCd: '009', catSmlNm: 'その他'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '006', catLrgNm: '法人向けサービス', catMidCd: '006', catMidNm: '研修', catSmlCd: '001', catSmlNm: 'ビジネス研修'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '006', catLrgNm: '法人向けサービス', catMidCd: '006', catMidNm: '研修', catSmlCd: '002', catSmlNm: '研修施設'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '006', catLrgNm: '法人向けサービス', catMidCd: '007', catMidNm: '住宅', catSmlCd: '002', catSmlNm: '社宅'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '007', catLrgNm: '生活', catMidCd: '011', catMidNm: '相談・サポート', catSmlCd: '001', catSmlNm: 'トラブルサポート'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '007', catLrgNm: '生活', catMidCd: '011', catMidNm: '相談・サポート', catSmlCd: '002', catSmlNm: '相談サービス'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '007', catLrgNm: '生活', catMidCd: '013', catMidNm: '通信', catSmlCd: '001', catSmlNm: 'プロバイダー'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '007', catLrgNm: '生活', catMidCd: '013', catMidNm: '通信', catSmlCd: '002', catSmlNm: 'オンラインサービス'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '007', catLrgNm: '生活', catMidCd: '013', catMidNm: '通信', catSmlCd: '003', catSmlNm: '携帯電話'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '007', catLrgNm: '生活', catMidCd: '014', catMidNm: '写真・プリント', catSmlCd: '001', catSmlNm: '写真・プリント'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '007', catLrgNm: '生活', catMidCd: '018', catMidNm: 'リサイクル・レンタルサービス', catSmlCd: '001', catSmlNm: 'リサイクル・レンタルサービス'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '007', catLrgNm: '生活', catMidCd: '021', catMidNm: 'ギフト', catSmlCd: '001', catSmlNm: 'フラワーギフト'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '007', catLrgNm: '生活', catMidCd: '021', catMidNm: 'ギフト', catSmlCd: '002', catSmlNm: 'カタログギフト・その他ギフト'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '007', catLrgNm: '生活', catMidCd: '021', catMidNm: 'ギフト', catSmlCd: '003', catSmlNm: '商品券・ギフト券'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '007', catLrgNm: '生活', catMidCd: '023', catMidNm: '葬儀・葬祭', catSmlCd: '001', catSmlNm: '葬儀・葬祭'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '007', catLrgNm: '生活', catMidCd: '024', catMidNm: 'フィナンス', catSmlCd: '001', catSmlNm: '各種ライフプラン相談'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '007', catLrgNm: '生活', catMidCd: '025', catMidNm: '住まい', catSmlCd: '002', catSmlNm: 'ガーデニング・防災'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '007', catLrgNm: '生活', catMidCd: '026', catMidNm: '家事・ハウスクリーニング', catSmlCd: '002', catSmlNm: 'ハウスクリーニング'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '007', catLrgNm: '生活', catMidCd: '026', catMidNm: '家事・ハウスクリーニング', catSmlCd: '001', catSmlNm: 'クリーニング・修理'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '007', catLrgNm: '生活', catMidCd: '027', catMidNm: '引越し', catSmlCd: '001', catSmlNm: '引越し'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '007', catLrgNm: '生活', catMidCd: '034', catMidNm: 'エネルギー', catSmlCd: '001', catSmlNm: '電力・ガス'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '007', catLrgNm: '生活', catMidCd: '034', catMidNm: 'エネルギー', catSmlCd: '002', catSmlNm: 'その他エネルギー'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '007', catLrgNm: '生活', catMidCd: '035', catMidNm: 'ペット', catSmlCd: '003', catSmlNm: 'ペット 企画・イベント'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '007', catLrgNm: '生活', catMidCd: '035', catMidNm: 'ペット', catSmlCd: '004', catSmlNm: 'ペット トリミング・宿泊'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '007', catLrgNm: '生活', catMidCd: '035', catMidNm: 'ペット', catSmlCd: '005', catSmlNm: 'ペット しつけ教室・シッター'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '007', catLrgNm: '生活', catMidCd: '035', catMidNm: 'ペット', catSmlCd: '006', catSmlNm: 'ペット 専門店'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '007', catLrgNm: '生活', catMidCd: '035', catMidNm: 'ペット', catSmlCd: '007', catSmlNm: 'ペット 葬儀'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '007', catLrgNm: '生活', catMidCd: '035', catMidNm: 'ペット', catSmlCd: '008', catSmlNm: 'ペット 検診・病院・保険'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '007', catLrgNm: '生活', catMidCd: '035', catMidNm: 'ペット', catSmlCd: '009', catSmlNm: 'ペット サポートサービス'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '027', catLrgNm: 'ハウジング', catMidCd: '001', catMidNm: '賃貸', catSmlCd: '001', catSmlNm: '賃貸'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '027', catLrgNm: 'ハウジング', catMidCd: '002', catMidNm: '購入', catSmlCd: '001', catSmlNm: '購入'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '027', catLrgNm: 'ハウジング', catMidCd: '003', catMidNm: 'リフォーム', catSmlCd: '001', catSmlNm: 'リフォーム'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '012', catLrgNm: 'BSオリジナル企画', catMidCd: '001', catMidNm: 'BSオリジナル企画', catSmlCd: '001', catSmlNm: 'その他オリジナル企画'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '012', catLrgNm: 'BSオリジナル企画', catMidCd: '001', catMidNm: 'BSオリジナル企画', catSmlCd: '005', catSmlNm: 'イベント・セミナー'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '012', catLrgNm: 'BSオリジナル企画', catMidCd: '001', catMidNm: 'BSオリジナル企画', catSmlCd: '007', catSmlNm: '慶事お祝い'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '012', catLrgNm: 'BSオリジナル企画', catMidCd: '001', catMidNm: 'BSオリジナル企画', catSmlCd: '008', catSmlNm: '株主優待'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '012', catLrgNm: 'BSオリジナル企画', catMidCd: '001', catMidNm: 'BSオリジナル企画', catSmlCd: '009', catSmlNm: '問合せ'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '012', catLrgNm: 'BSオリジナル企画', catMidCd: '002', catMidNm: 'ベネポ', catSmlCd: '001', catSmlNm: 'ベネポ'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '012', catLrgNm: 'BSオリジナル企画', catMidCd: '003', catMidNm: '募金', catSmlCd: '001', catSmlNm: '募金'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '023', catLrgNm: '各種手続き・その他', catMidCd: '001', catMidNm: 'ガイドブック', catSmlCd: '001', catSmlNm: 'ガイドブック'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '023', catLrgNm: '各種手続き・その他', catMidCd: '003', catMidNm: 'その他', catSmlCd: '001', catSmlNm: 'その他特典'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '023', catLrgNm: '各種手続き・その他', catMidCd: '002', catMidNm: '会員証', catSmlCd: '004', catSmlNm: '会員証'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '026', catLrgNm: '出会い・ブライダル', catMidCd: '001', catMidNm: 'ブライダル', catSmlCd: '001', catSmlNm: '結婚式場'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '026', catLrgNm: '出会い・ブライダル', catMidCd: '001', catMidNm: 'ブライダル', catSmlCd: '002', catSmlNm: 'リング'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '026', catLrgNm: '出会い・ブライダル', catMidCd: '001', catMidNm: 'ブライダル', catSmlCd: '003', catSmlNm: 'ドレス'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '026', catLrgNm: '出会い・ブライダル', catMidCd: '001', catMidNm: 'ブライダル', catSmlCd: '004', catSmlNm: '海外ウェディング'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '026', catLrgNm: '出会い・ブライダル', catMidCd: '001', catMidNm: 'ブライダル', catSmlCd: '005', catSmlNm: '二次会'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '026', catLrgNm: '出会い・ブライダル', catMidCd: '001', catMidNm: 'ブライダル', catSmlCd: '008', catSmlNm: 'その他ブライダル'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '026', catLrgNm: '出会い・ブライダル', catMidCd: '001', catMidNm: 'ブライダル', catSmlCd: '009', catSmlNm: '写真・ビデオ・演出'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '026', catLrgNm: '出会い・ブライダル', catMidCd: '001', catMidNm: 'ブライダル', catSmlCd: '010', catSmlNm: '参列者向けサービス'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '026', catLrgNm: '出会い・ブライダル', catMidCd: '002', catMidNm: '出会い', catSmlCd: '001', catSmlNm: '結婚情報'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '026', catLrgNm: '出会い・ブライダル', catMidCd: '002', catMidNm: '出会い', catSmlCd: '002', catSmlNm: 'お見合いパーティ'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '026', catLrgNm: '出会い・ブライダル', catMidCd: '002', catMidNm: '出会い', catSmlCd: '003', catSmlNm: 'その他出会い'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '026', catLrgNm: '出会い・ブライダル', catMidCd: '002', catMidNm: '出会い', catSmlCd: '005', catSmlNm: 'ネット婚活'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '028', catLrgNm: 'カー', catMidCd: '001', catMidNm: 'レンタカー・リース', catSmlCd: '001', catSmlNm: 'レンタカー'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '028', catLrgNm: 'カー', catMidCd: '001', catMidNm: 'レンタカー・リース', catSmlCd: '002', catSmlNm: 'カーリース'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '028', catLrgNm: 'カー', catMidCd: '001', catMidNm: 'レンタカー・リース', catSmlCd: '003', catSmlNm: 'カーシェアリング'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '028', catLrgNm: 'カー', catMidCd: '002', catMidNm: '車検・修理・整備', catSmlCd: '001', catSmlNm: '車検・修理・整備'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '028', catLrgNm: 'カー', catMidCd: '003', catMidNm: 'カーサービス', catSmlCd: '001', catSmlNm: '駐車場'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '028', catLrgNm: 'カー', catMidCd: '003', catMidNm: 'カーサービス', catSmlCd: '002', catSmlNm: 'タクシー・送迎サービス'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '028', catLrgNm: 'カー', catMidCd: '003', catMidNm: 'カーサービス', catSmlCd: '003', catSmlNm: 'ガソリンスタンド'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '028', catLrgNm: 'カー', catMidCd: '003', catMidNm: 'カーサービス', catSmlCd: '004', catSmlNm: 'カー用品'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '028', catLrgNm: 'カー', catMidCd: '003', catMidNm: 'カーサービス', catSmlCd: '005', catSmlNm: 'その他カーサービス'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '028', catLrgNm: 'カー', catMidCd: '004', catMidNm: '免許・教習所', catSmlCd: '001', catSmlNm: '免許・教習所'},
  {catExlCd: 'others', catExlNm: 'その他', catLrgCd: '028', catLrgNm: 'カー', catMidCd: '005', catMidNm: '新車・中古車販売・買取', catSmlCd: '001', catSmlNm: '新車・中古車販売・買取'},
  {catExlCd: 'leisure', catExlNm: '遊ぶ', catLrgCd: '003', catLrgNm: 'レジャー・エンタメ', catMidCd: '012', catMidNm: 'スポーツ観戦', catSmlCd: '001', catSmlNm: '野球'},
  {catExlCd: 'leisure', catExlNm: '遊ぶ', catLrgCd: '003', catLrgNm: 'レジャー・エンタメ', catMidCd: '012', catMidNm: 'スポーツ観戦', catSmlCd: '002', catSmlNm: 'サッカー'},
  {catExlCd: 'leisure', catExlNm: '遊ぶ', catLrgCd: '003', catLrgNm: 'レジャー・エンタメ', catMidCd: '012', catMidNm: 'スポーツ観戦', catSmlCd: '003', catSmlNm: 'その他スポーツ観戦'},
  {catExlCd: 'leisure', catExlNm: '遊ぶ', catLrgCd: '003', catLrgNm: 'レジャー・エンタメ', catMidCd: '013', catMidNm: 'エンターテインメント', catSmlCd: '001', catSmlNm: 'ボウリング'},
  {catExlCd: 'leisure', catExlNm: '遊ぶ', catLrgCd: '003', catLrgNm: 'レジャー・エンタメ', catMidCd: '013', catMidNm: 'エンターテインメント', catSmlCd: '002', catSmlNm: 'カラオケ・インターネットカフェ'},
  {catExlCd: 'leisure', catExlNm: '遊ぶ', catLrgCd: '003', catLrgNm: 'レジャー・エンタメ', catMidCd: '013', catMidNm: 'エンターテインメント', catSmlCd: '003', catSmlNm: 'その他エンターテインメント'},
  {catExlCd: 'leisure', catExlNm: '遊ぶ', catLrgCd: '003', catLrgNm: 'レジャー・エンタメ', catMidCd: '014', catMidNm: 'チケット', catSmlCd: '001', catSmlNm: '演劇・舞台'},
  {catExlCd: 'leisure', catExlNm: '遊ぶ', catLrgCd: '003', catLrgNm: 'レジャー・エンタメ', catMidCd: '014', catMidNm: 'チケット', catSmlCd: '002', catSmlNm: 'コンサート'},
  {catExlCd: 'leisure', catExlNm: '遊ぶ', catLrgCd: '003', catLrgNm: 'レジャー・エンタメ', catMidCd: '014', catMidNm: 'チケット', catSmlCd: '003', catSmlNm: 'その他チケット'},
  {catExlCd: 'leisure', catExlNm: '遊ぶ', catLrgCd: '003', catLrgNm: 'レジャー・エンタメ', catMidCd: '015', catMidNm: 'レジャー', catSmlCd: '001', catSmlNm: 'レジャー'},
  {catExlCd: 'leisure', catExlNm: '遊ぶ', catLrgCd: '003', catLrgNm: 'レジャー・エンタメ', catMidCd: '015', catMidNm: 'レジャー', catSmlCd: '002', catSmlNm: 'アウトドアレジャー'},
  {catExlCd: 'leisure', catExlNm: '遊ぶ', catLrgCd: '003', catLrgNm: 'レジャー・エンタメ', catMidCd: '015', catMidNm: 'レジャー', catSmlCd: '003', catSmlNm: 'その他レジャー'},
  {catExlCd: 'leisure', catExlNm: '遊ぶ', catLrgCd: '003', catLrgNm: 'レジャー・エンタメ', catMidCd: '018', catMidNm: '映画', catSmlCd: '001', catSmlNm: '劇場鑑賞券'},
  {catExlCd: 'leisure', catExlNm: '遊ぶ', catLrgCd: '003', catLrgNm: 'レジャー・エンタメ', catMidCd: '018', catMidNm: '映画', catSmlCd: '002', catSmlNm: '映画作品'},
  {catExlCd: 'gourmet', catExlNm: '食べる', catLrgCd: '011', catLrgNm: 'グルメ', catMidCd: '002', catMidNm: '情報サービス', catSmlCd: '001', catSmlNm: '情報サービス'},
  {catExlCd: 'gourmet', catExlNm: '食べる', catLrgCd: '011', catLrgNm: 'グルメ', catMidCd: '003', catMidNm: '食事券', catSmlCd: '001', catSmlNm: '食事券'},
  {catExlCd: 'gourmet', catExlNm: '食べる', catLrgCd: '011', catLrgNm: 'グルメ', catMidCd: '004', catMidNm: '飲食店', catSmlCd: '048', catSmlNm: '居酒屋'},
  {catExlCd: 'gourmet', catExlNm: '食べる', catLrgCd: '011', catLrgNm: 'グルメ', catMidCd: '004', catMidNm: '飲食店', catSmlCd: '049', catSmlNm: 'ダイニングバー'},
  {catExlCd: 'gourmet', catExlNm: '食べる', catLrgCd: '011', catLrgNm: 'グルメ', catMidCd: '004', catMidNm: '飲食店', catSmlCd: '050', catSmlNm: 'ＢＡＲ・ビアガーデン'},
  {catExlCd: 'gourmet', catExlNm: '食べる', catLrgCd: '011', catLrgNm: 'グルメ', catMidCd: '004', catMidNm: '飲食店', catSmlCd: '018', catSmlNm: '和食'},
  {catExlCd: 'gourmet', catExlNm: '食べる', catLrgCd: '011', catLrgNm: 'グルメ', catMidCd: '004', catMidNm: '飲食店', catSmlCd: '052', catSmlNm: '焼肉・ホルモン'},
  {catExlCd: 'gourmet', catExlNm: '食べる', catLrgCd: '011', catLrgNm: 'グルメ', catMidCd: '004', catMidNm: '飲食店', catSmlCd: '053', catSmlNm: '鍋'},
  {catExlCd: 'gourmet', catExlNm: '食べる', catLrgCd: '011', catLrgNm: 'グルメ', catMidCd: '004', catMidNm: '飲食店', catSmlCd: '054', catSmlNm: 'そば・うどん'},
  {catExlCd: 'gourmet', catExlNm: '食べる', catLrgCd: '011', catLrgNm: 'グルメ', catMidCd: '004', catMidNm: '飲食店', catSmlCd: '055', catSmlNm: '丼もの'},
  {catExlCd: 'gourmet', catExlNm: '食べる', catLrgCd: '011', catLrgNm: 'グルメ', catMidCd: '004', catMidNm: '飲食店', catSmlCd: '056', catSmlNm: '定食・食堂'},
  {catExlCd: 'gourmet', catExlNm: '食べる', catLrgCd: '011', catLrgNm: 'グルメ', catMidCd: '004', catMidNm: '飲食店', catSmlCd: '015', catSmlNm: '軽食'},
  {catExlCd: 'gourmet', catExlNm: '食べる', catLrgCd: '011', catLrgNm: 'グルメ', catMidCd: '004', catMidNm: '飲食店', catSmlCd: '058', catSmlNm: '洋食・欧風料理'},
  {catExlCd: 'gourmet', catExlNm: '食べる', catLrgCd: '011', catLrgNm: 'グルメ', catMidCd: '004', catMidNm: '飲食店', catSmlCd: '059', catSmlNm: 'カレー'},
  {catExlCd: 'gourmet', catExlNm: '食べる', catLrgCd: '011', catLrgNm: 'グルメ', catMidCd: '004', catMidNm: '飲食店', catSmlCd: '021', catSmlNm: 'イタリア料理'},
  {catExlCd: 'gourmet', catExlNm: '食べる', catLrgCd: '011', catLrgNm: 'グルメ', catMidCd: '004', catMidNm: '飲食店', catSmlCd: '020', catSmlNm: 'フランス料理'},
  {catExlCd: 'gourmet', catExlNm: '食べる', catLrgCd: '011', catLrgNm: 'グルメ', catMidCd: '004', catMidNm: '飲食店', catSmlCd: '062', catSmlNm: 'スペイン料理'},
  {catExlCd: 'gourmet', catExlNm: '食べる', catLrgCd: '011', catLrgNm: 'グルメ', catMidCd: '004', catMidNm: '飲食店', catSmlCd: '063', catSmlNm: '西洋料理'},
  {catExlCd: 'gourmet', catExlNm: '食べる', catLrgCd: '011', catLrgNm: 'グルメ', catMidCd: '004', catMidNm: '飲食店', catSmlCd: '023', catSmlNm: '中国料理'},
  {catExlCd: 'gourmet', catExlNm: '食べる', catLrgCd: '011', catLrgNm: 'グルメ', catMidCd: '004', catMidNm: '飲食店', catSmlCd: '065', catSmlNm: '韓国料理'},
  {catExlCd: 'gourmet', catExlNm: '食べる', catLrgCd: '011', catLrgNm: 'グルメ', catMidCd: '004', catMidNm: '飲食店', catSmlCd: '066', catSmlNm: 'アジア・エスニック'},
  {catExlCd: 'gourmet', catExlNm: '食べる', catLrgCd: '011', catLrgNm: 'グルメ', catMidCd: '004', catMidNm: '飲食店', catSmlCd: '067', catSmlNm: 'ブッフェ・バイキング'},
  {catExlCd: 'gourmet', catExlNm: '食べる', catLrgCd: '011', catLrgNm: 'グルメ', catMidCd: '004', catMidNm: '飲食店', catSmlCd: '068', catSmlNm: 'ラーメン・つけ麺・ちゃんぽん'},
  {catExlCd: 'gourmet', catExlNm: '食べる', catLrgCd: '011', catLrgNm: 'グルメ', catMidCd: '004', catMidNm: '飲食店', catSmlCd: '069', catSmlNm: '自然・薬膳・野菜'},
  {catExlCd: 'gourmet', catExlNm: '食べる', catLrgCd: '011', catLrgNm: 'グルメ', catMidCd: '004', catMidNm: '飲食店', catSmlCd: '070', catSmlNm: 'カフェ・スイーツ'},
  {catExlCd: 'gourmet', catExlNm: '食べる', catLrgCd: '011', catLrgNm: 'グルメ', catMidCd: '004', catMidNm: '飲食店', catSmlCd: '071', catSmlNm: 'ファミレス・ファーストフード'},
  {catExlCd: 'gourmet', catExlNm: '食べる', catLrgCd: '011', catLrgNm: 'グルメ', catMidCd: '004', catMidNm: '飲食店', catSmlCd: '072', catSmlNm: 'デリバリー'},
  {catExlCd: 'gourmet', catExlNm: '食べる', catLrgCd: '011', catLrgNm: 'グルメ', catMidCd: '004', catMidNm: '飲食店', catSmlCd: '073', catSmlNm: 'テイクアウト'},
  {catExlCd: 'gourmet', catExlNm: '食べる', catLrgCd: '011', catLrgNm: 'グルメ', catMidCd: '004', catMidNm: '飲食店', catSmlCd: '028', catSmlNm: 'エンターテインメント'},
  {catExlCd: 'gourmet', catExlNm: '食べる', catLrgCd: '011', catLrgNm: 'グルメ', catMidCd: '004', catMidNm: '飲食店', catSmlCd: '047', catSmlNm: 'その他'},
  {catExlCd: 'care', catExlNm: '育児・介護・健康', catLrgCd: '014', catLrgNm: '健康', catMidCd: '001', catMidNm: '健診・相談', catSmlCd: '003', catSmlNm: '健康相談'},
  {catExlCd: 'care', catExlNm: '育児・介護・健康', catLrgCd: '014', catLrgNm: '健康', catMidCd: '001', catMidNm: '健診・相談', catSmlCd: '004', catSmlNm: 'メンタルヘルス'},
  {catExlCd: 'care', catExlNm: '育児・介護・健康', catLrgCd: '014', catLrgNm: '健康', catMidCd: '001', catMidNm: '健診・相談', catSmlCd: '005', catSmlNm: '健診サービス'},
  {catExlCd: 'care', catExlNm: '育児・介護・健康', catLrgCd: '014', catLrgNm: '健康', catMidCd: '001', catMidNm: '健診・相談', catSmlCd: '007', catSmlNm: 'その他健診'},
  {catExlCd: 'care', catExlNm: '育児・介護・健康', catLrgCd: '014', catLrgNm: '健康', catMidCd: '001', catMidNm: '健診・相談', catSmlCd: '008', catSmlNm: '郵送検診'},
  {catExlCd: 'care', catExlNm: '育児・介護・健康', catLrgCd: '014', catLrgNm: '健康', catMidCd: '002', catMidNm: '健康管理', catSmlCd: '000', catSmlNm: '眼科'},
  {catExlCd: 'care', catExlNm: '育児・介護・健康', catLrgCd: '014', catLrgNm: '健康', catMidCd: '002', catMidNm: '健康管理', catSmlCd: '001', catSmlNm: '歯科'},
  {catExlCd: 'care', catExlNm: '育児・介護・健康', catLrgCd: '014', catLrgNm: '健康', catMidCd: '002', catMidNm: '健康管理', catSmlCd: '002', catSmlNm: '健康グッズ・食品'},
  {catExlCd: 'care', catExlNm: '育児・介護・健康', catLrgCd: '014', catLrgNm: '健康', catMidCd: '002', catMidNm: '健康管理', catSmlCd: '004', catSmlNm: 'その他'},
  {catExlCd: 'care', catExlNm: '育児・介護・健康', catLrgCd: '014', catLrgNm: '健康', catMidCd: '002', catMidNm: '健康管理', catSmlCd: '008', catSmlNm: '美容医療'},
  {catExlCd: 'care', catExlNm: '育児・介護・健康', catLrgCd: '024', catLrgNm: '育児', catMidCd: '003', catMidNm: '育児サービス', catSmlCd: '001', catSmlNm: '育児用品'},
  {catExlCd: 'care', catExlNm: '育児・介護・健康', catLrgCd: '024', catLrgNm: '育児', catMidCd: '003', catMidNm: '育児サービス', catSmlCd: '002', catSmlNm: 'その他（育児）'},
  {catExlCd: 'care', catExlNm: '育児・介護・健康', catLrgCd: '024', catLrgNm: '育児', catMidCd: '003', catMidNm: '育児サービス', catSmlCd: '003', catSmlNm: '育児補助制度'},
  {catExlCd: 'care', catExlNm: '育児・介護・健康', catLrgCd: '024', catLrgNm: '育児', catMidCd: '003', catMidNm: '育児サービス', catSmlCd: '004', catSmlNm: 'フォトサービス'},
  {catExlCd: 'care', catExlNm: '育児・介護・健康', catLrgCd: '024', catLrgNm: '育児', catMidCd: '004', catMidNm: '託児・ベビーシッター', catSmlCd: '001', catSmlNm: '育児施設・学童'},
  {catExlCd: 'care', catExlNm: '育児・介護・健康', catLrgCd: '024', catLrgNm: '育児', catMidCd: '004', catMidNm: '託児・ベビーシッター', catSmlCd: '002', catSmlNm: 'ベビーシッター'},
  {catExlCd: 'care', catExlNm: '育児・介護・健康', catLrgCd: '024', catLrgNm: '育児', catMidCd: '012', catMidNm: '教育・セミナー', catSmlCd: '002', catSmlNm: '教育'},
  {catExlCd: 'care', catExlNm: '育児・介護・健康', catLrgCd: '024', catLrgNm: '育児', catMidCd: '012', catMidNm: '教育・セミナー', catSmlCd: '003', catSmlNm: 'セミナー'},
  {catExlCd: 'care', catExlNm: '育児・介護・健康', catLrgCd: '025', catLrgNm: '介護', catMidCd: '002', catMidNm: '介護', catSmlCd: '000', catSmlNm: '在宅介護'},
  {catExlCd: 'care', catExlNm: '育児・介護・健康', catLrgCd: '025', catLrgNm: '介護', catMidCd: '002', catMidNm: '介護', catSmlCd: '001', catSmlNm: '介護施設'},
  {catExlCd: 'care', catExlNm: '育児・介護・健康', catLrgCd: '025', catLrgNm: '介護', catMidCd: '002', catMidNm: '介護', catSmlCd: '002', catSmlNm: '介護用品'},
  {catExlCd: 'care', catExlNm: '育児・介護・健康', catLrgCd: '025', catLrgNm: '介護', catMidCd: '002', catMidNm: '介護', catSmlCd: '003', catSmlNm: 'その他（介護）'},
  {catExlCd: 'care', catExlNm: '育児・介護・健康', catLrgCd: '025', catLrgNm: '介護', catMidCd: '002', catMidNm: '介護', catSmlCd: '004', catSmlNm: '見守りサービス'},
  {catExlCd: 'care', catExlNm: '育児・介護・健康', catLrgCd: '025', catLrgNm: '介護', catMidCd: '002', catMidNm: '介護', catSmlCd: '005', catSmlNm: '介護タクシー'},
  {catExlCd: 'care', catExlNm: '育児・介護・健康', catLrgCd: '025', catLrgNm: '介護', catMidCd: '002', catMidNm: '介護', catSmlCd: '006', catSmlNm: '宅配・宅食'},
]